
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

_inputs:
  textarea_html:
    options:
      options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6
      italic: true
      strike: true
      underline: true 
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      image: true
      undo: true
      redo: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Banner
        icon: star
        value: 
          _section-type: banner
          banner_image: 
          logo_image: 
          sub-heading: 
          call-to-action: 
          button-link: 
          content-block-id: 
      - label: Space
        icon: block
        value: 
          _section-type: space-block
          background-color: 
      