
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

_inputs:
  textarea_html:
    options:
      options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6
      italic: true
      strike: true
      underline: true 
      link: true
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      styles: /custom-styles.css
      left: left
      center: center
      right: right
      justify: justify
      image: true
      undo: true
      redo: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Hero
        icon: star
        value: 
          _section-type: hero
          hero_image: /images/banner.webp
          logo_image: /images/logo.PNG
          subheading: adventure with purpose
          call-to-action: LET'S GO!
          button-link: /#about 
          content-block-link: /
      - label: Space
        icon: block
        value: 
          _section-type: space-block
          background-color: 'white'
      - label: Blog Article 
        icon: view_headline
        value:
          _section-type: blog-article
          textarea_html: <h3 class="center">Portfolio</h3>
          colors:
            background-color: white
            text-color: rgb(83, 83, 83)
            heading-color: rgb(83, 83, 83)
            subheading-color: rgb(83, 83, 83)
            link-color: '#A2B7C0'
            link-hover-color: '#C09D8A'
          fonts:
            heading-font: Lovelace Regular
            subheading-font: Lovelace Regular
            text-font: The Youngest Serif  
      - label: Text On The Left
        icon: left_panel_open
        value:
          _section-type: text-on-the-left
          heading: BONJOUR
          subheading: Hello! <br> I am Name Surname
          textarea_html: >-
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Praesentium
            blanditiis omnis cupiditate. Provident dolores quis sit, velit corporis,
            libero quod explicabo, veniam necessitatibus consectetur quae. Asperiores
            nam possimus pariatur rerum? Lorem ipsum dolor sit amet consectetur,
            adipisicing elit. Praesentium blanditiis omnis cupiditate. Provident
            dolores quis sit, velit corporis, libero quod explicabo, veniam
            necessitatibus consectetur quae. Asperiores nam possimus pariatur rerum?</p>
          image: /images/about.webp
    content-block-link: about
      - label: Slide in from the Right 
        icon: east
        value: 
          _section-type: slide-in-from-right
          heading: Travel
          textarea_html: >-
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi omnis totam,
            qui perferendis aut officiis sequi aspernatur cupiditate labore dolores
            molestiae fuga nesciunt voluptatibus saepe? Quam perferendis omnis iusto
            repellendus. </p>
          button-link: /portfolio.html#travel-portfolio
          image: /images/travel-1.webp
          icon_image: /illustrations/thick-squiggle.png
          content-block-link: portfolio-1
      - label: Slide in from the Left 
        icon: west
        value: 
          _section-type: slide-in-from-left
          heading: Real Estate
          textarea_html: >-
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi omnis totam,
            qui perferendis aut officiis sequi aspernatur cupiditate labore dolores
            molestiae fuga nesciunt voluptatibus saepe? Quam perferendis omnis iusto
            repellendus.</p>
          button-link: /portfolio.html#real-estate-portfolio
          image: /images/real-estate-5.webp
          icon_image: /illustrations/thick-squiggle.png
          content-block-link: portfolio-2
      - label: Text in the middle
        icon: width-wide
        value:
          _section-type: text-in-the-middle
          left_image: /images/what-i-do-1.webp
          heading: what i do
          textarea_html: >-
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Non dicta
            asperiores fuga optio? Fugiat ullam fugit nulla, maiores molestiae quas
            nostrum recusandae ut inventore harum et enim maxime quasi
            voluptatibus.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Non
            dicta asperiores fuga optio? Fugiat ullam fugit nulla, maiores molestiae
            quas nostrum recusandae ut inventore harum et enim maxime quasi
            voluptatibus. Lorem ipsum dolor sit, amet consectetur adipisicing elit.
            Non dicta asperiores fuga optio? Fugiat ullam fugit nulla, maiores
            molestiae quas nostrum recusandae ut inventore harum et enim maxime quasi
            voluptatibus.</p>
          button-link: /contact
          call-to-action: contact me
          right_image: /images/what-i-do-2.webp
          content-block-link: what-i-do
      - label: Portfolio
        icon: view_comfy
        value:
          _section-type: portfolio-block
          subheading: Underwater Photography
          gallery:
            1_image: /images/underwater-1.webp
            2_image: /images/underwater-2.webp
            3_image: /images/underwater-3.webp
            4_image: /images/underwater-4.webp
            5_image: /images/underwater-5.webp
          textarea_html: <p>adventure with purpose</p>
          call-to-action: Contact Me
          call-to-action-link: /contact
          colors:
            call-to-action-background-color: '#c1d6df'
            background-color: '#e2e4e6'
            button-color: '#A2B7C0'
            border-color: '#e2e4e6'
          content-block-link: underwater-portfolio
      - label: form
        icon: mail
        value:
          _section-type: form
          background_image: /images/banner.webp
          top-left_image: /images/about.webp
          top-left_illustration: /illustrations/thin-squiggle.png
          heading: Contact Me
          form-input:
            option-box.option-1: Name and Surname 
            option-box.option-1: Email
            option-box.option-1: What Service do you require?
          button-cta: Send
          bottom-right_image: /images/travel-5.webp
          content-block-link: 

fonts:
_select_data:
  fonts:
      - Lovelace Regular
      - The Youngest Serif



            