
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

_inputs:
  textarea_html:
    options:
      options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6
      italic: true
      strike: true
      underline: true 
      link: true
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      styles: /custom-styles.css
      left: left
      center: center
      right: right
      justify: justify
      image: true
      undo: true
      redo: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Hero
        icon: star
        value: 
          _section-type: hero
          hero_image: /images/banner.webp
          logo_image: /images/logo.PNG
          subheading: adventure with purpose
          call-to-action: LET'S GO!
          button-link: /#about 
          content-block-link: /
      - label: Space
        icon: block
        value: 
          _section-type: space-block
          background-color: 'white'
      - label: Blog Article 
        icon: view_headline
        value:
          _section-type: blog-article
          textarea_html: <h1>Portfolio</h1>
          colors:
            background-color: 'white'
            text-color: 'rgb(83, 83, 83)'
            heading-color: 'rgb(83, 83, 83)'
            subheading-color: 'rgb(83, 83, 83)'
            link-color: '#A2B7C0'
            link-hover-color: '#C09D8A' 
          fonts:
            heading-font: Lovelace Regular
            subheading-font: Lovelace Regular
            text-font: The Youngest Serif   
      - label: Text On The Left
        icon: left_panel_open
        value:
          _section-type: text-on-the-left
          heading: 
          subheading: 
          textarea_html: 
          image: 
          content-block-id: 
      - label: Slide in from the Right 
        icon: left_panel_open
        value: 
          _section-type: slide-in-from-right
          heading: 
          textarea_html: 
          button-link: 
          image: 
          icon: 
          content-block-link:
      - label: Slide in from the Left 
        icon: west
        value: 
          _section-type: slide-in-from-left
          heading: 
          textarea_html:
          button-link:  
          image: 
          icon: 
      - label: Text in the middle
        icon: width-wide
        value:
          _section-type: text-in-the-middle 
          left_image: 
          heading: 
          textarea_html: 
          button-link: 
          call-to-action: 
          right_image: 
          content-block-id: 
      - label: Portfolio
        icon: view_comfy
        value:
          _section-type: portfolio-block
          subheading: Travel Photography
          gallery:
            1_image: /images/travel-1.webp
            2_image: /images/travel-2.webp
            3_image: /images/travel-3.webp
            4_image: /images/travel-4.webp
            5_image: /images/travel-5.webp
          textarea_html: <p>adventure with purpose</p>
          call-to-action: Contact Me
          call-to-action-link: /contact
          colors:
            call-to-action-background-color: '#c1d6df'
            background-color: '#e2e4e6'
            border-color: '#e2e4e6'
          content-block-link: travel-portfolio
      - label: form
        icon: mail
        value:
          _section-type: form
          background_image: /images/banner.webp
          top-left_image: /images/about.webp
          top-left_illustration: /illustrations/thin-squiggle.png
          heading: Contact Me
          form-input:
            option-box.option-1: Name and Surname 
            option-box.option-1: Email
            option-box.option-1: What Service do you require?
          button-cta: Send
          bottom-right_image: /images/travel-5.webp
          content-block-link: 

fonts:
_select_data:
  fonts:
      - Lovelace Regular
      - The Youngest Serif



            