
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

_inputs:
  textarea_html:
    options:
      options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6
      italic: true
      strike: true
      underline: true 
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      image: true
      undo: true
      redo: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Banner
        icon: star
        value: 
          _section-type: banner
          banner_image: 
          logo_image: 
          sub-heading: 
          call-to-action:
          button-link: 
          content-block-id: 
      - label: Space
        icon: block
        value: 
          _section-type: space-block
          background-color: 
      - label: Text On The Left
        icon: left_panel_open
        value:
          _section-type: text-on-the-left
          heading: 
          sub-heading: 
          textarea_html: 
          image: 
          content-block-id: 
      - label: Slide in from the Right 
        icon: left_panel_open
        value: 
          _section-type: slide-in-from-right
          heading: 
          textarea_html: 
          button-link: 
          image: 
          icon: 
          content-block-link:
      - label: Slide in from the Left 
        icon: west
        value: 
          _section-type: slide-in-from-left
          heading: 
          textarea_html:
          button-link:  
          image: 
          icon: 
      - label: Recent Blogs
        icon: view_column
        value:
          _section-type: recent-blogs
          heading:
          colors:
            background-color:
            heading-color: 
            blog-title-card-color:
            blog-title-card-border-color: 
            blog-hover-overlay-color: 
            text-color:
            subheading-color:
            cta-color:
          fonts:
            text-font: 
            heading-font: 
            subheading-font: 
            cta-font:
      - label: Heading
        icon: position_top_right
        value:
          _section-type: heading
          heading:
          background-color: 
      - label: Text in the middle
        icon: width-wide
        value:
          _section-type: text-in-the-middle 
          left_image: 
          heading: 
          textarea_html: 
          button-link: 
          call-to-action: 
          right_image: 
          content-block-id: 
      - label: Portfolio
        icon: view_comfy
        value:
          _section-type: portfolio-block
          sub-heading:
          background-color:
          border-color:
          1_image:
          2_image:
          3_image:
          4_image:
          5_image:
          6_image:
          content-block-id: 
      - label: Contact
        icon: mail
        value:
          _section-type: contact-block
          background_image: 
          top-left_image: 
          top-left_illustration: 
          heading: 
          form-field-1_textarea_html: 
          form-field-2_textarea_html: 
          form-field-3_textarea_html: 
          button_textarea_html: 
          bottom-right_image: 
          content-block-id:


            