
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

_inputs:
  textarea_html:
    options:
      options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6
      italic: true
      strike: true
      underline: true 
      link: true
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      styles: /custom-styles.css
      left: left
      center: center
      right: right
      justify: justify
      image: true
      undo: true
      redo: true

page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Hero
        icon: star
        value: 
          _section-type: hero
          hero_image: /images/banner.webp
          logo_image: /images/logo.PNG
          subheading: adventure with purpose
          call-to-action: LET'S GO!
          button-link: /#about 
          content-block-link: /
      - label: Space
        icon: block
        value: 
          _section-type: space-block
          background-color: 
      - label: Text On The Left
        icon: left_panel_open
        value:
          _section-type: text-on-the-left
          heading: 
          subheading: 
          textarea_html: 
          image: 
          content-block-id: 
      - label: Slide in from the Right 
        icon: left_panel_open
        value: 
          _section-type: slide-in-from-right
          heading: 
          textarea_html: 
          button-link: 
          image: 
          icon: 
          content-block-link:
      - label: Slide in from the Left 
        icon: west
        value: 
          _section-type: slide-in-from-left
          heading: 
          textarea_html:
          button-link:  
          image: 
          icon: 
      - label: Plain Text Area
        icon: position_top_right
        value:
          _section-type: plain-text-area
          textarea_html:
          background-color: 
      - label: Text in the middle
        icon: width-wide
        value:
          _section-type: text-in-the-middle 
          left_image: 
          heading: 
          textarea_html: 
          button-link: 
          call-to-action: 
          right_image: 
          content-block-id: 
      - label: Portfolio
        icon: view_comfy
        value:
          _section-type: portfolio-block
          subheading:
          background-color:
          border-color:
          1_image:
          2_image:
          3_image:
          4_image:
          5_image:
          call-to-action-background-color:
          textarea_html: 
          call-to-action: 
          call-to-action-link: 
          content-block-id: 
      - label: form
        icon: mail
        value:
          _section-type: form
          background_image: /images/banner.webp
          top-left_image: /images/about.webp
          top-left_illustration: /illustrations/thin-squiggle.png
          heading: Contact Me
          form-input:
            option-box.option-1: Name and Surname 
            option-box.option-1: Email
            option-box.option-1: What Service do you require?
          button-cta: Send
          bottom-right_image: /images/travel-5.webp
          content-block-link: 



            